### PR TITLE
Use Go 1.19

### PR DESCRIPTION
**Pull request by abhinav**
This raises the `go` directive in the go.mod file to Go 1.19,
and runs `go mod tidy`,
which prunes a fair bit of redundant information from the go.sum.

Additionally, this bumps the version of Go used in both GitHub
workflows.

### CODE REVIEW

**Comment by saswatamcode** [comment]
Can you regenerate the README on this?

**Comment by abhinav** [comment]
Done! Weird; I didn't expect it to change with go 1.19.

**Comment by abhinav** [comment]
Gentle bump. I'll rebase #98 on top when this merges.

**Review by saswatamcode — APPROVED** [review]
LGTM!

**Pull request merged**
